apiVersion: v1
kind: Service
metadata:
  name: products-api
  labels:
    courselabs.co: project-cicd
    app: widgetario
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: widgetario
    component: products-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  labels:
    courselabs.co: project-cicd
    app: widgetario
spec:
  replicas: 2
  selector:
    matchLabels:
        app: widgetario
        component: products-api
  template:
    metadata:
      labels:
        app: widgetario
        component: products-api
    spec:
      containers:
        - name: app
          image: widgetario/products-api:21.12
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http