apiVersion: v1
kind: Service
metadata:
  name: stock-api
  labels:
    courselabs.co: project-cicd
    app: widgetario
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: widgetario
    component: stock-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
  labels:
    courselabs.co: project-cicd
    app: widgetario
spec:
  replicas: 2
  selector:
    matchLabels:
        app: widgetario
        component: stock-api
  template:
    metadata:
      labels: 
        app: widgetario
        component: stock-api
    spec:
      containers:
        - name: app
          image: widgetario/stock-api:21.12
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http