apiVersion: v1
kind: Service
metadata:
  name: products-db
  labels:
    courselabs.co: project-cicd
    app: widgetario
spec:
  ports:
    - port: 5432
      targetPort: postgres
  selector:
    app: widgetario
    component: products-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  labels:
    courselabs.co: project-cicd
    app: widgetario
spec:
  selector:
    matchLabels:
      app: widgetario
      component: products-db
  replicas: 1
  template:
    metadata:
      labels:
        app: widgetario
        component: products-db
    spec:     
      containers:
        - name: app
          image: widgetario/products-db:21.12
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: postgres